### ISSUE TITLE
Read / query path pointed to by junction reparse point

### ISSUE THREAD

**Issue by Erotemic** [jaraco/jaraco.windows#12]
I'm attempting to use `jaraco.windows.filesystem.readlink` to find the target location pointed to by a junction. However, using this function errors because 

```
RuntimeError: Expected IO_REPARSE_TAG_SYMLINK, but got 2684354563
```

However, if I step into the function at about here: 
https://github.com/jaraco/jaraco.windows/blob/2031b058eb0a199a1122d71400045451b73132ed/jaraco/windows/filesystem/__init__.py#L390

and look at the contents of `rdb.get_substitute_name()`, it seems to have the correct path, except its prefixed with `?\\`. 

The fact that it seems to read the junction correctly makes me believe that the tag 2684354563 corresponds to something meaningful about a junction. Not sure what that is as I don't often use windows, but it seems this function could be modified to return links to junctions (or at least another function could be written to do so).

**Comment by jaraco** [comment]
That tag corresponds to:

```
>>> hex(2684354563)
'0xa0000003'
>>> bin(2684354563)
'0b10100000000000000000000000000011'
```

Looking at [the docs for the tags](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365511(v=vs.85).aspx), and [this reference](https://msdn.microsoft.com/en-us/library/dd541667.aspx), it seems that tag corresponds to IO_REPARSE_TAG_MOUNT_POINT.

I think you may be right that `readlink` can support that form also. Would you be willing to put together a PR?
