### ISSUE TITLE
clipboard is gone?

### ISSUE THREAD

**Issue by cmougin** [jaraco/jaraco.windows#17]
Hi Jaraco,
I have a small tool relying on jaraco.clipboard that I discovered a few months ago.
the method paste_html() was doing an excellent job… until it recently vanished!
what happened, did you withdraw or move it?
I look forward to reading you,
Christophe

**Comment by jaraco** [comment]
Looking at the clipboard module, nothing has changed significantly since 2018. Can you share what code you were using that stopped working? Are you sure you were using `jaraco.windows` directly and not `jaraco.clipboard` (which relies on `jaraco.windows` for Windows)?
